name: Deploy Vite App to EC2

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Install Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3️⃣ Install dependencies & build
      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      # 4️⃣ Deploy to EC2
      - name: Copy files to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          source: "dist/*"
          target: "~/my-vite-app"

      # 5️⃣ Restart Nginx on EC2
      - name: Restart Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            sudo rm -rf /var/www/html/*
            sudo cp -r ~/my-vite-app/* /var/www/html/
            sudo systemctl restart nginx
